name: demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-VariableFont_wght.ttf
  assets:
     - assets/images/chicken_noodles.webp
     - assets/images/paneer.webp
     - assets/images/biri.webp
     - assets/images/fish_curry.webp
     - assets/images/egg.webp
     - assets/images/mutton.webp
     - assets/images/masala.webp
     - assets/images/butter.webp
     - assets/images/swiggy.png